repos:
  # Ruff
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.6
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  # Pytest
  - repo: local
    hooks:
      - id: pytest-check
        name: Run all tests
        entry: pytest
        language: python
        pass_filenames: false
        always_run: true
        types: [python]
        args:
          - --cov=econ_capital          # measure coverage of code
          - --cov-config=.coveragerc    # coverage testing settings
          - --cov-fail-under=90         # fail commit if coverage drops
          - --cov-report=term-missing   # if failed show which lines are missing
          - --maxfail=1                 # stop on first failure
          - --tb=short                  # clean traceback
        additional_dependencies:
          - pytest
          - pytest-cov
          - numpy
          - pandas
          - scipy
          - arch
          - pyyaml
          - openpyxl
          - yfinance
          - fredapi>=0.5.2 
          - tqdm
          - setuptools
          - pandas>=2.2.1
          - matplotlib
          - python-dotenv

  # Nbstriput - strip Notebook outputs
  -   repo: https://github.com/kynan/nbstripout
      rev: 0.8.0
      hooks:
      -   id: nbstripout
          name: Strip notebook outputs
          description: Clear outputs from Jupyter notebooks before commit
          entry: nbstripout
          language: python
          types: [jupyter]